ndjek1/pahappa-goals-bucket

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/organization_structure/Department.java
backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/organization_structure/Team.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/organization_structure_services/DepartmentService.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/organization_structure_services/Impl/DepartmentServiceImpl.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/organization_structure_services/Impl/TeamServiceImpl.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/organization_structure_services/TeamService.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/security/HyperLinks.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/organizationstructure/DepartmentFormDialog.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/organizationstructure/OrganizationStructureView.java
frontend/kpi-tracker-web/src/main/resources/applicationContext-server.xml
frontend/kpi-tracker-web/src/main/resources/hibernate.cfg.xml
frontend/kpi-tracker-web/src/main/webapp/pages/californiatemplate/sidebar.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/organizationstructure/DepartmentFormDialog.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/organizationstructure/OrganizationStructure.xhtml

=> These are elements or foundational components of the organizational feature.
###Some changes
=> Made one of the hyperlinks more general; (services.*)

the organization structure feature

---

frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/users/RegistrationView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/users/UserFormDialog.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/users/UsersView.java
frontend/kpi-tracker-web/src/main/webapp/ExternalViews/Login.xhtml
frontend/kpi-tracker-web/src/main/webapp/ExternalViews/Register.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/users/UsersView.xhtml

This pull request introduces a complete user self-registration and administrator approval workflow. It includes a new registration page, updates to the login page, and the necessary backend logic for administrators to manage new sign-ups.
Key Features:
- User Registration:
A new, styled registration page (Register.xhtml) has been added, allowing users to create their own accounts.
A corresponding backing bean (RegistrationView.java) handles the form submission and saves new users with a "Pending" status.
- Login Page Update:
The login page has been restyled to match the modern look and feel of the new registration page, creating a consistent user experience.
A prominent link to the registration page has been added.
- Admin Approval System:
The user management table view has been …

Feat: Implement User Registration and Approval Workflow

---

frontend/kpi-tracker-web/src/main/webapp/pages/californiatemplate/sidebar.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/californiatemplate/template.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/californiatemplate/topbar.xhtml
frontend/kpi-tracker-web/src/main/webapp/resources/california-layout/js/layout.js

This pull request introduces a complete refactoring of the main application layout, specifically targeting the sidebar, topbar, and the core template.
The primary tasks completed are:
- Structural Refactoring: The XHTML for the sidebar and topbar has been modernized using CSS Flexbox. This provides a more robust and maintainable structure, allowing for better alignment of components, such as pinning the "Sign Out" button to the bottom of the sidebar.
- Responsive Behavior: New JavaScript has been added to manage the sidebar's state. On smaller viewports (mobile/tablet), the sidebar now collapses into a hamburger menu, which can be toggled to show or hide the navigation pane. This significantly improves the user experience on devices with limited screen width.
Bug fix (non-breaking change …

Refactor: Modernize Sidebar and Topbar Layout with Dynamic JS

---

backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/kpis/KpisService.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/kpis/impl/KpisServiceImpl.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/kpis/kpisImpl/KpisServiceImpl.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/Dashboard.java

- Created KpisService interface extending GenericService<KPI>
- Added getObjectById(String var1) method
- Implemented KpisServiceImpl extending GenericServiceImpl<KPI>
- Annotated with @Service and @Transactional
- Implemented saveInstance with validation and persistence
- Implemented isDeletable (default returns true, customizable later)
- Implemented getObjectById to retrieve KPI by ID

feat(kpi-service): implement KPI service layer

---

backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/systemUsers/SystemUserService.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/systemUsers/impl/SystemUserServiceImpl.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/organizationstructure/DepartmentMembersView.java
frontend/kpi-tracker-web/src/main/webapp/pages/organizationstructure/ManageMembers.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/organizationstructure/OrganizationStructure.xhtml

implemented the page or view for managing of department members

Ft department members view organization structure

---

.vscode/settings.json
frontend/kpi-tracker-web/src/main/webapp/pages/californiatemplate/sidebar.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/kpis/DepartmentKPIView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/kpis/KPIForm.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/kpis/KPIView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/kpis/TeamKPIView.xhtml

- Added sidebar navigation with role-based access
- Created KPIView, KPIForm, DepartmentKPIView, TeamKPIView pages
- Applied consistent design conventions from organization structure
- Implemented CRUD, search, and role-based filtering features

feat: Implement KPI management system

---

frontend/kpi-tracker-web/src/main/webapp/pages/activities/ActivitiesView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/DepartmentActivitiesView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/TeamActivitiesView.xhtml

• Replace non-existent statistics properties with dynamic calculations using activityModels.stream() .
• Remove references to currentDepartment and currentTeam properties that don't exist in Java views.
• Fix status filter dropdown by removing non-existent recordStatusList property.
• Ensure all activities XHTML files render without 'Property not found' EL exceptions .
• Maintain UI functionality while using only properties that exist in Java view classes

fix: resolve property not found errors in Activities XHTML files

---

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/systemSetup/enums/MeasurementUnit.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/security/HyperLinks.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/ActivitiesView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/ActivityFormDialog.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/DepartmentActivitiesView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/TeamActivitiesView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/dialogs/DialogForm.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/kpis/DepartmentKPIView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/kpis/KPIForm.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/kpis/KPIView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/kpis/TeamKPIView.java
frontend/kpi-tracker-web/src/main/java/org/pahappa/systems/client/converters/ActivityStatusConverter.java
frontend/kpi-tracker-web/src/main/java/org/pahappa/systems/client/converters/DepartmentGoalConverter.java
frontend/kpi-tracker-web/src/main/java/org/pahappa/systems/client/converters/FrequencyConverter.java
frontend/kpi-tracker-web/src/main/java/org/pahappa/systems/client/converters/MeasurementUnitConverter.java
frontend/kpi-tracker-web/src/main/java/org/pahappa/systems/client/converters/TeamGoalConverter.java
frontend/kpi-tracker-web/src/main/webapp/pages/activities/ActivitiesView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/ActivityFormDialog.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/DepartmentActivitiesView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/TeamActivitiesView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/kpis/DepartmentKPIView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/kpis/KPIForm.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/kpis/KPIView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/kpis/TeamKPIView.xhtml

- Reduce top margin from 60px to 20px for better button positioning
- Change button column width from p-col-2 to p-col-1 for compact layout
- Add 10px right margin between Cancel and Save buttons for clear separation
- Reduce button width from 100px to 80px with custom padding (8px 16px)
- Improve overall button accessibility and visual hierarchy in 3-column form layout
Resolves: Button visibility and spacing issues in activity form dialog
Type: UI/UX improvement

fix: improve button visibility in add activity form dialog

---

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/systemSetup/ReviewCycle.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/ActivityFormDialog.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/dialogs/systemSetup/ReviewCycleForm.java
frontend/kpi-tracker-web/src/main/webapp/pages/systemSetup/GlobalWeightTable.xhtml

This pull request contains mostly code cleaning
Managing exceptions, added check for null-ability
Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
Unit

Just cleaning up code here

---

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/systemUsers/SystemUser.java
frontend/kpi-tracker-web/src/main/webapp/pages/users/UserFormDialog.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/users/UsersView.xhtml

Updating user management by making assignment to department at creation optional, and removed setting ajax to false.
Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
Unit
Integration
Login as an admin, Go to manage users, clik add user ,
fill in the details and don't choose a department and click save, 
the user should be saved correctly

Chore: Cleaning code in user management feature

---

frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/ActivityFormDialog.java

 revert role based in kpis and manage activities in viewing goals

---

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/activities/Activity.java
backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/systemSetup/enums/ActivityPriority.java
backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/systemSetup/enums/ActivityType.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/DepartmentActivitiesView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/DepartmentActivityFormDialog.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/OrganizationalActivitiesView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/OrganizationalActivityFormDialog.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/TeamActivitiesView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/TeamActivityFormDialog.java
frontend/kpi-tracker-web/src/main/java/org/pahappa/systems/client/converters/ActivityPriorityConverter.java
frontend/kpi-tracker-web/src/main/java/org/pahappa/systems/client/converters/ActivityTypeConverter.java
frontend/kpi-tracker-web/src/main/webapp/pages/activities/ActivitiesView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/DepartmentActivityFormDialog.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/OrganizationalActivityFormDialog.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/README.md
frontend/kpi-tracker-web/src/main/webapp/pages/activities/TeamActivityFormDialog.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/californiatemplate/sidebar.xhtml

• Add ActivityPriority and ActivityType enums with proper display names and database constraints.
• Update Activity model with priority and activityType fields, default values, and proper JPA annotations.
• Fix XML parsing error in ActivitiesView.xhtml by correcting malformed h:outputText element

feat: Integrate Activity Priority and Type Enums with Backend Model

---

frontend/kpi-tracker-web/src/main/webapp/pages/activities/DepartmentActivitiesView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/californiatemplate/sidebar.xhtml

- Reorganized sidebar menu structure to group related functionality by organizational context
- Moved organizational KPIs and activities under 'Manage Goals' section for administrators
- Added department KPIs and activities under 'Manage Department' section for department leaders
- Added team KPIs and activities under 'Manage Team' section for team leaders
- Eliminated duplicate menu items from 'Manage KPIs' and 'Manage Activities' sections

feat: restructure sidebar with goal-context organization for better UX

---

frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/systemSetup/OrgFitCategoryView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/users/UserFormDialog.java
frontend/kpi-tracker-web/src/main/webapp/ExternalViews/Login.xhtml
frontend/kpi-tracker-web/src/main/webapp/ExternalViews/Register.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/systemSetup/GlobalWeightForm.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/systemSetup/ThresholdForm.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/users/UserFormDialog.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/users/UsersView.xhtml

=> Full details of the tasks in the PR

Fixed and issue that happens when creating a new. 

---

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/activities/Activity.java
backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/kpis/KPI.java

ity
- Add IndividualGoal field to KPI with JPA mapping.
- Add IndividualGoal field to Activity with JPA mappi ng.
- Include getters/setters and imports; lints clean.

feat(models): add IndividualGoal refs to KPI and Activ

---

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/goals/IndividualGoal.java

- Refined individual goal model with proper mapping
-

fix(models): replace Staff with User in IndividualGoal mapping

---

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/goals/OrganizationGoal.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/security/HyperLinks.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/OrganizationGoalForm.java
frontend/kpi-tracker-web/src/main/webapp/pages/californiatemplate/sidebar.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/goals/OrganizationGoalForm.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/goals/OrganizationGoalsView.xhtml

Updating the organization goal management feature. CHanging logic and ui 

Updating the organization goal feature

---

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/systemUsers/Staff.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/systemUsers/StaffService.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/systemUsers/impl/StaffServiceImpl.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/security/UiUtils.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/users/RegistrationView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/users/UserFormDialog.java

Making some cange on the user management feature

Updating user management feature

---

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/goals/IndividualGoal.java
backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/security/PermissionConstants.java
backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/security/RoleConstants.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/impl/CustomPermissionRoleMigrations.java
frontend/kpi-tracker-web/src/main/webapp/pages/californiatemplate/topbar.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/goals/goalDetails.xhtml

Updating roles and permissions , individual goal model and top bar

Updating the roles and permissions , individual goal goals details 

---

frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/TeamsView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/organizationstructure/TeamForm.java
frontend/kpi-tracker-web/src/main/resources/hibernate.cfg.xml
frontend/kpi-tracker-web/src/main/webapp/pages/organizationstructure/DepartmentTeams.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/organizationstructure/TeamForm.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/organizationstructure/TeamsView.xhtml

Added feature for team management

Added feature for team management

---

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/staff/Staff.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/systemUsers/StaffService.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/systemUsers/impl/StaffServiceImpl.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/users/RegistrationView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/users/UserFormDialog.java

Changed package name, and added few other details

Refactor : staff management feature

---

frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/security/HyperLinks.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/organizationstructure/DepartmentMembersView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/organizationstructure/DepartmentTeamsView.java
frontend/kpi-tracker-web/src/main/webapp/pages/organizationstructure/OrganizationStructure.xhtml

Added view for viewing teams of a department and fixed few problems from HyperLinks.java

Refator: Organization structure 

---

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/staff/Staff.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/organizationstructure/TeamForm.java
frontend/kpi-tracker-web/src/main/java/org/pahappa/systems/client/converters/StaffConverter.java
frontend/kpi-tracker-web/src/main/webapp/pages/organizationstructure/TeamForm.xhtml

Update the team management feature and added the ability to add people to a team and assign a lead

Update the team management feature 

---

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/activities/TeamActivity.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/activities/TeamActivityService.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/activities/impl/TeamActivityServiceImpl.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/TeamActivitiesView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/TeamActivityFormDialog.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/UpdateTeamActivityDialog.java
frontend/kpi-tracker-web/src/main/webapp/pages/activities/TeamActivitiesView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/TeamActivityFormDialog.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/UpdatedTeamActivityDialog.xhtml

Changed the activity management structure, added team activity management

Feature: team activity management

---

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/activities/IndividualActivity.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/activities/IndividualActivityService.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/activities/impl/IndividualActivityServiceImpl.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/IndividualActivitiesView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/IndividualActivityForm.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/UpdateIndividualActivityDialog.java
frontend/kpi-tracker-web/src/main/webapp/pages/activities/IndividualActivitiesView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/IndividualActivityFormDialog.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/UpdateIndividualActivityDialog.xhtml

Changed the activity management structure, added individual activity management

Feature: individual activity management 

---

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/kpis/KPI.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/kpis/DepartmentKPIView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/kpis/IndividualKPIView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/kpis/TeamKPIView.java
frontend/kpi-tracker-web/src/main/webapp/pages/kpis/DepartmentKPIView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/kpis/IndividualKPIView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/kpis/TeamKPIView.xhtml

Changed the kpi model and put mappings on getters, fixed fea bugs on views and ui

bugs: fixed bugs on kpi managements.

---

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/organization_structure/Department.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/kpis/KpiDetailView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/organizationstructure/DepartmentFormDialog.java
frontend/kpi-tracker-web/src/main/webapp/pages/goals/DepartmentGoalView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/kpis/KpiDetailView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/systemSetup/OrgFitCategoryForm.xhtml

Fixed a bug related to the kpi details view.

Bug:Fixed a bug related to the kpi details view.

---

frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/dialogs/systemSetup/ThresholdForm.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/systemSetup/ThresholdView.java
frontend/kpi-tracker-web/src/main/webapp/pages/systemSetup/OrgFitCategoryForm.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/systemSetup/OrgFitCategoryItemTable.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/systemSetup/OrgFitCategoryTable.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/systemSetup/ThresholdForm.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/systemSetup/ThresholdTable.xhtml

Styling organization fit categories and threshold feature and fixing logic in the process of saving or updating

Refactor: user interface and logic in organization fit categories and thresholds

---

backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/impl/OrgFitCategoryMigration.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/organizationstructure/DepartmentFormDialog.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/users/UserFormDialog.java
frontend/kpi-tracker-web/src/main/webapp/pages/californiatemplate/dialog-template.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/californiatemplate/sidebar.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/organizationstructure/DepartmentFormDialog.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/organizationstructure/OrganizationStructure.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/users/UserFormDialog.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/users/UsersView.xhtml

Styling and fixing responsiveness of the department management feature and fixed few issues in user management

Refactor:Styling user interface

---

frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/IndividualActivitiesView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/IndividualActivityForm.java
frontend/kpi-tracker-web/src/main/webapp/pages/activities/IndividualActivitiesView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/IndividualActivityFormDialog.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/goals/IndividualGoalForm.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/goals/IndividualGoalsView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/kpis/IndividualKPIForm.xhtml

Fixing user interface for individual level components

Refactor:Fixing user interface for individual level components

---

frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/DepartmentGoalDetails.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/GoalDetails.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/IndividualGoalDetails.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/TeamGoalDetails.java
frontend/kpi-tracker-web/src/main/webapp/pages/goals/IndividualGoalDetails.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/goals/TeamGoalDetails.xhtml

Styling goals details page, added a donut model to show progress of goal

Refactor: Styling gal details

---

frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/DepartmentGoalDetails.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/GoalDetails.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/IndividualGoalForm.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/TeamGoalForm.java
frontend/kpi-tracker-web/src/main/webapp/pages/goals/IndividualGoalForm.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/goals/TeamGoalForm.xhtml

Making sure that contribution weights of child goals should not exceed 100 percent

Refactor: adding validation to goal creation

---

frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/DepartmentGoalsForm.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/OrganizationGoalForm.java
frontend/kpi-tracker-web/src/main/webapp/pages/californiatemplate/dialog-template.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/goals/DepartmentGoalForm.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/goals/OrganizationGoalForm.xhtml

Just Styling dialog forms for goal setting

Refactor:Styling dialog forms.

---

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/systemSetup/GlobalWeight.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/systemSetupService/GlobalWeightService.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/systemSetupService/impl/GlobalWeightServiceImpl.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/dialogs/systemSetup/GlobalWeightForm.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/systemSetup/GlobalWeightView.java
frontend/kpi-tracker-web/src/main/webapp/pages/systemSetup/GlobalWeightForm.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/systemSetup/GlobalWeightTable.xhtml

Updated global weights management.

Refactor  global weights management.

---

frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/organizationstructure/DepartmentTeamsView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/organizationstructure/TeamMembersView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/organizationstructure/TeamsView.java
frontend/kpi-tracker-web/src/main/webapp/pages/organizationstructure/DepartmentTeams.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/organizationstructure/OrganizationStructure.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/organizationstructure/TeamMembers.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/organizationstructure/TeamsView.xhtml

Updated organization structure management. Department and team management including adding members

Refactor organization structure management(departments and teams)

---

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/systemSetup/Threshold.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/systemSetupService/ThresholdService.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/systemSetupService/impl/ThresholdServiceImpl.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/dialogs/systemSetup/ThresholdForm.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/systemSetup/ThresholdView.java
frontend/kpi-tracker-web/src/main/webapp/pages/systemSetup/ThresholdForm.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/systemSetup/ThresholdTable.xhtml

Updated threshold management by adding new fields and responsiveness.#### Type of change

Refactor threshold management.

---

backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/activities/DepartmentActivity.java
backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/activities/IndividualActivity.java
backend/kpi-tracker-models/src/main/java/org/pahappa/systems/kpiTracker/models/activities/TeamActivity.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/DepartmentActivitiesView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/IndividualActivitiesView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/TeamActivitiesView.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/UpdateDepartmentActivityForm.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/UpdateIndividualActivityDialog.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/activities/UpdateTeamActivityDialog.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/IndividualGoalDetails.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/TeamGoalDetails.java
frontend/kpi-tracker-web/src/main/webapp/pages/activities/DepartmentActivitiesView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/DepartmentActivityFormDialog.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/IndividualActivitiesView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/IndividualActivityFormDialog.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/TeamActivitiesView.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/TeamActivityFormDialog.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/UpdateActivityDialog.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/UpdateIndividualActivityDialog.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/activities/UpdatedTeamActivityDialog.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/goals/IndividualGoalDetails.xhtml
frontend/kpi-tracker-web/src/main/webapp/pages/goals/TeamGoalDetails.xhtml

Updated activity management

---

frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/GoalDetails.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/kpis/KPIForm.java
frontend/kpi-tracker-web/src/main/webapp/pages/californiatemplate/sidebar.xhtml

Updated kpi form and goalDetails beans and sidebar

Updated kpi form and goalDetails beans and sidebar

---

backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/kpis/KpisService.java
backend/kpi-tracker-services/src/main/java/org/pahappa/systems/kpiTracker/core/services/kpis/impl/KpisServiceImpl.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/DepartmentGoalDetails.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/GoalDetails.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/IndividualGoalDetails.java
frontend/kpi-tracker-views/src/main/java/org/pahappa/systems/kpiTracker/views/goals/TeamGoalDetails.java

Updating calculation of goal progress.

Updating calculation of goal progress.

---

frontend/kpi-tracker-web/src/main/webapp/pages/californiatemplate/sidebar.xhtml

=> Full details of the tasks in the PR

spelling correction of staff from 'staffs'
